### ISSUE TITLE
爱来自瓷器 不过有些东西变了

### ISSUE THREAD

**Issue by mzmrikka** [HuntercodeT/NWAFU-NCOV-AutoDailyCheck#1]
部分代码被弃用了

**Comment by rld2014** [comment]
把`broser.find_element_by_xpath()`换成`browser.find_element(By.XPATH, ...)`就OK了，记得`from selenium.webdriver.common.by import By`

**Comment by HuntercodeT** [comment]
是的，selenium升级大版本了，我改个代码
